[project]
name = "pydantic-ai-laughing-doodle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai[logfire]>=0.4.2",
    "pyright>=1.1.403",
]
